stages:
  load_data:
    cmd: python src/stage_01_load.py --config=config/config.yaml
    deps:
      - src/stage_01_load.py
      - config/config.yaml
      - src/utils/all_utils.py

    outs:
      - data

  split_data:
    cmd: python src/stage_02.py --config=config/config.yaml

    deps:
      - src/stage_02.py
      - config/config.yaml
      - src/utils/all_utils.py
      - data
    outs:
      - test
      - train_data
      - val_data

  preprocess:
    cmd: python src/stage_03.py --config=config/config.yaml

    deps:
      - src/stage_03.py
      - config/config.yaml
      - src/utils/all_utils.py
      - test
      - train_data
      - val_data

    outs:
      - test_crop
      - test_crop
      - val_crop

  prepare_model:
    cmd: python src/stage_04.py --config=config/config.yaml --params= params.yaml

    deps:
      - src/stage_04.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/config.yaml

    outs:
      - artifacts/base_model/vgg16_base_model.h5
      - artifacts/base_model/update_vgg16.h5


    


    