stages:
  load_data:
    cmd: python src/stage_01_load.py --config=config/config.yaml
    deps:
      - src/stage_01_load.py
      - config/config.yaml
      - src/utils/all_utils.py

    outs:
      - data

  split_data:
    cmd: python src/stage_02.py --config=config/config.yaml

    deps:
      - src/stage_02.py
      - config/config.yaml
      - src/utils/all_utils.py
      - data
    outs:
      - test
      - train_data
      - val_data

  preprocess:
    cmd: python src/stage_03.py --config=config/config.yaml

    deps:
      - src/stage_03.py
      - config/config.yaml
      - src/utils/all_utils.py
      - test
      - train_data
      - val_data

    outs:
      - test_crop
      - test_crop
      - val_crop

    


    