stages:
  load_data:
    cmd: python src/stage_01_load.py --config=config/config.yaml
    deps:
      - src/stage_01_load.py
      - config/config.yaml
      - src/utils/all_utils.py

    outs:
      - data

  split_data:
    cmd: python src/stage_02.py --config=config/config.yaml

    deps:
      - src/stage_02.py
      - config/config.yaml
      - src/utils/all_utils.py
      - data
    outs:
      - test
      - train_data
      - val_data

  preprocess:
    cmd: python src/stage_03.py --config=config/config.yaml

    deps:
      - src/stage_03.py
      - config/config.yaml
      - src/utils/all_utils.py
      - test
      - train_data
      - val_data

    outs:
      - test_crop
      - test_crop
      - val_crop

  prepare_model:
    cmd: python src/stage_04.py --config=config/config.yaml --params=params.yaml

    deps:
      - src/stage_04.py
      - src/utils/all_utils.py
      - src/utils/model.py
      - config/config.yaml

    params:
      - IMAGE_SIZE
      - LEARNING_RATE

    outs:
      - artifacts/base_model/vgg16_base_model.h5
      - artifacts/base_model/update_vgg16.h5

  prepare_callback:
    cmd: python src/stage_05.py --config=config/config.yaml --params=params.yaml

    deps:
      - src/stage_05.py
      - src/utils/all_utils.py
      - src/utils/callback.py
      - config/config.yaml

    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
      - artifacts/callbacks/early_stopping.cb


  train_model:
    cmd: python src/stage_06.py --config=config/config.yaml --params=params.yaml

    deps:
      - src/stage_06.py
      - src/utils/all_utils.py
      - src/utils/callback.py
      - src/utils/model.py
      - config/config.yaml
      - test_crop
      - train_crop
      - val_crop
      - artifacts/base_model/update_vgg16.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
      - artifacts/callbacks/early_stopping.cb


    outs:
      - artifacts/model



    


    


    