artifacts:
  artifacts_dir: artifacts
  test_data_dir: test/
  train_data_dir: train_data/
  val_data_dir: val_data/

  test_crop_dir: test_crop/
  train_crop_dir : train_crop/
  val_crop_dir: val_crop

  train_model_dir: model
  base_model_dir: base_model
  base_model_name: vgg16_base_model.h5
  update_base_model_name: update_vgg16.h5
  checkpoint_dir: checkpoints
  callback_dir: callbacks





source_data_dir:
  - ../brain_tumor_dataset/yes
  - ../brain_tumor_dataset/no


data_dirs:
  - data/yes
  - data/no

test_dir: 
  - test/yes
  - test/no
train_dirs:
  - train_data/yes
  - train_data/no
val_dirs:
  - val_data/yes
  - val_data/no

test_dir_crop:
  - test_crop/yes
  - test_crop/no

train_dir_crop:
  - train_crop/yes
  - train_crop/no

val_dir_crop:
  - val_crop/yes
  - val_crop/no



